### ISSUE TITLE
[Bug]: Facing error in rendering the login dashboard

### ISSUE THREAD

**Issue by ashwinexe** [Sawo-Community/Initial-Contributors-Projects#8]
### Detailed Description

I found this error in this project where the Login Dashboard won't show up on using Sawo for a React App
Code currently under my fork [here](https://github.com/ashwinexe/Initial-Contributors-Projects/tree/main/Projects/react-component)

### Expected Behavior

I expected a dashboard like this  
![image](https://user-images.githubusercontent.com/53075480/163031347-a04dccba-33b7-467c-b0b4-f41186aa7d54.png)

### Current Behavior

Instead of showing the dashboard, I find an error like below
![image](https://user-images.githubusercontent.com/53075480/163031422-9017a4cd-7cb5-4c1f-9344-9079b8986339.png)

### How can someone reproduce the behavior?

1. Goto https://docs.sawolabs.com/sawo/single-page/react-component
2. Follow the steps to create the initial dashboard
3. Add the API Key
4. Run the React Project

### What was you environment (os, browser, runtime, etc)?

Windows 10  Chrome Latest, Node14

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Anything else?

My SAWO Dashboard looks like this, I kept the hostname on default, not sure if that's causing the issue
![image](https://user-images.githubusercontent.com/53075480/163031903-3909ecbf-e7d7-42bc-8cfa-a8a300d04d0e.png)

**Comment by Sonichigo** [comment]
@ashwinexe Hostname should be 'localhost' 
Can u try that once and check?

**Comment by ashwinexe** [comment]
Did that, not success. On the browser console, this is the error message
 `Failed to load resource: the server responded with a status of 429 ()`

**Comment by Sonichigo** [comment]
That mean you have been rate limited by server. made too many requests in short period of time! Try making a new project from dashboard and use it's api-key in your project.

**Comment by ashwinexe** [comment]
Thanks, @Sonichigo I have resolved the issue. Chrome was listing the SAWO script as insecure. 
This was fixed by adding `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` to index whitelisting the script and allowing API to work properly on dev environment.
